### ISSUE TITLE
lexer can block before returning last token

### ISSUE THREAD

**Issue by bebac** [crystal-community/msgpack-crystal#19]
If reading from an IO, say a socket, that is not closed the lexer will block on next_byte if there is no more data currently available. F.ex if one is sending a stream of integers.

Here is a snippet from next_token

```
    when 0xE0..0xFF
      @token.type = :INT
      @token.int_value = current_byte.to_i8
      next_byte
```

If that int is the last byte available next_byte blocks and the just read token is not returned.

I think it is also a problem that next_byte is called from the lexer constructor. This means that constructing an Unpacker can actually block if there is no data available.

**Comment by benoist** [comment]
If I'm not mistaken this can be handled by setting the read timeout on the socket.

**Comment by bebac** [comment]
I do not think a timeout on the read is the answer. What if the other end does not have anymore data to send for a while. A useless example would be a server periodically sending an integer say every 60s. 

I think the lexer should not read from the IO until the unpacker actually asks for data.

**Comment by benoist** [comment]
Is this what you meant?

**Comment by bebac** [comment]
Wow that was fast :-) Yes it was something like that. I am not sure it solves it completely though. I hacked up this little example to illustrate. Maybe I got it wrong but it doesn't see the last int.

```
require "socket"
require "msgpack"

def process(client)
  puts "client connected"
  unpacker = MessagePack::Unpacker.new(client)

  loop do
    v = unpacker.read_value
    puts "server received #{v}"
  end
ensure
  client.close
end

server = TCPServer.new "127.0.0.1", 9000

socket = TCPSocket.new "127.0.0.1", 9000
packer = MessagePack::Packer.new(socket)

(1..3).each do |i|
  packer.write(i)
  puts "client wrote #{i}"
end

loop { spawn process(server.accept) }
```

Output:

```
client wrote 1
client wrote 2
client wrote 3
client connected
server received 1
server received 2

```

**Comment by benoist** [comment]
Right, the unpacker is doing the same as the lexer was. Adding this example as a test and then I will fix the unpacker.

**Comment by bebac** [comment]
Excellent!

**Comment by benoist** [comment]
I've created a new branch with the new spec that now passes, but for now I had to introduce a new parser to make the mapping work.
