### ISSUE TITLE
Allow to write hash and array by parts

### ISSUE THREAD

**Issue by kostya** [crystal-community/msgpack-crystal#3]
is it possible to write like this? to save us from create temp hashes, arrays of Type.

``` crystal
packer.write_hash_start
packer.write_hash_key("bla")
packer.write_hash_value(123)
packer.write_hash_key("bla2")
packer.write_hash_value(true)
packer.write_hash_end

packer.write_array_start
packer.write_array_element("bla")
packer.write_array_element(123)
packer.write_array_element("bla2")
packer.write_array_element(true)
packer.write_array_end

```

**Comment by benoist** [comment]
That's not possible (yet). The reason this won't work is because you need to know the size of the hash and array. The size is stored before the first key or item is written.

**Comment by kostya** [comment]
length also ok.
if i can:

``` crystal
packer.write_hash_start(2)
packer.write_hash_key("bla")
packer.write_hash_value(123)
packer.write_hash_key("blab")
packer.write_hash_value(123)
```

**Comment by benoist** [comment]
Sure that can definitely be added.

**Comment by kostya** [comment]
this is needed because even this not compiled:

```
packer = MessagePack::Packer.new

x = {"a" => 1, "b" => [1, 2] }

packer.write(x)
puts packer.to_slice
```

**Comment by benoist** [comment]
correct, for now you'd have to write:

``` crystal
packer = MessagePack::Packer.new
x = Hash(MessagePack::Type, MessagePack::Type){"a" => 1, "b" => Array(MessagePack::Type){1, 2}}

packer.write(x)
puts packer.to_slice
```

**Comment by kostya** [comment]
but if you get hash from variable, you would need to create another one temp hash with Type, Type

**Comment by benoist** [comment]
Yeah this has something to do with the type alias. I'm not really sure why, but it doesn't accept hashes that only contain MessagePack::Type keys and values if it's not specifically defined.
