### ISSUE TITLE
Add support for type extension

### ISSUE THREAD

**Issue by bew** [crystal-community/msgpack-crystal#44]
Detailed here: https://github.com/msgpack/msgpack/blob/master/spec.md#extension-types
And the binary format here: https://github.com/msgpack/msgpack/blob/master/spec.md#ext-format-family

> MessagePack allows applications to define application-specific types using the Extension type.
> Extension type consists of an integer and a byte array where the integer represents a kind of types and the byte array represents data.
>
> Applications can assign `0` to `127` to store application-specific type information. An example usage is that application defines `type = 0` as the application's unique type system, and stores name of a type and values of the type at the payload.
>
> MessagePack reserves `-1` to `-128` for future extension to add predefined types. These types will be added to exchange more types without using pre-shared statically-typed schema across different programming environments.
>
> ```
> [0, 127]: application-specific types
> [-128, -1]: reserved for predefined types
> ```
>
> Because extension types are intended to be added, old applications may not implement all of them. However, they can still handle such type as one of Extension types. Therefore, applications can decide whether they reject unknown Extension types, accept as opaque data, or transfer to another application without touching payload of them.

I was thinking we could pass some informations about custom types to the (un)packer (and to/from_msgpack) ?

_Note: I haven't put much thoughts about it, and I don't really know how the current msgpack implementation works_

**Comment by kostya** [comment]
why you need user types? any real example? I can imagine only for implement some sort of marshaling (which is crystal lacks off).

**Comment by bew** [comment]
Yes, I need this to implement the neovim RPC API, you can read about the custom types needed here: https://neovim.io/doc/user/msgpack_rpc.html#rpc-types (section `Special types`)

**Comment by kostya** [comment]
v 0.14.0 support type extensions, example: https://github.com/crystal-community/msgpack-crystal/blob/master/examples/ext.cr

btw, there is shard for msgpack-rpc: https://github.com/kostya/simple_rpc

**Comment by bew** [comment]
Awesome thank you @kostya!!
Your msgpack-rpc shard looks promising, I'll prob' use that :smiley:
