### ISSUE TITLE
The fix of #49 doesn't cover type restriction.

### ISSUE THREAD

**Issue by xqyww123** [crystal-community/msgpack-crystal#50]
```
data = ({aa: "a", bb: nil}).to_msgpack
typeof(NamedTuple(aa: String, bb: Nil).from_msgpack(data)[:aa]) # => (String | Nil) but should be just `String`
```
And this breaks my compiler type-check.

_Originally posted by @xqyww123 in https://github.com/crystal-community/msgpack-crystal/issue_comments#issuecomment-441992829_

**Comment by kostya** [comment]
fixed in 0.11.1 by https://github.com/crystal-community/msgpack-crystal/commit/f7ca99388485af76d437099aa41ece7e505d6030
